###############################################

# Font and Symbols and Cursor
#font_family JetBrainsMono Nerd Font
font_family FiraCode Nerd Font
font_size 15
# block / beam / underline
cursor_shape underline

# Window
window_margin_width 6
single_window_margin_width 2

#background_image /home/gabriel-sousa/.config/kitty/background_anime.png
background_image_layout scaled
# active_border_color #6600cc
window_border_width 2pt

dynamic_background_opacity yes
background_opacity 0.82

background_tint 0.7 
background_tint_gaps -10
backgorund #BE1D1A
# foreground #BE1D1A

tab_bar_style powerline
tab_powerline_style slanted

# Key Mapping and Bindings
map ctrl+plus change_font_size all +0.5
map ctrl+minus change_font_size all -0.5
map ctrl+0 change_font_size all 0

map f1 new_windwo_with_cwd

###############################################



# BEGIN_KITTY_THEME
# Adwaita dark
include current-theme.conf
# END_KITTY_THEME
