# ~/.config/ranger/rc.conf

# Set Neovim as the default editor
set editor nvim
set visual nvim

# Show hidden files (dotfiles)
set show_hidden true

# Enable image previews using ueberzug (requires Python3 and ueberzug installed)
set preview_images true
set preview_images_method ueberzug

# Enable preview for different file types (text, PDF, etc.)
set preview_files true

# Set the default command for opening files (e.g., nvim for editing)
map <C-e> shell zsh
map <C-t> shell tmux

# Filetype-based preview
set preview_files true
#set preview_files_limit 50

# Enabling preview of files (text, images, PDFs, etc.)
set preview_directories true

# Keybindings to toggle between preview modes
map zh console set show_hidden !show_hidden

# Allow previewing when navigating directories
#set preview_thumbnails true

# Set the default file manager command to open a file (nvim by default)
set open_command nvim
